# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-10 13:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sysadmin', '0002_auto_20161009_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailupdate',
            name='sent',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='emailupdate',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 10, 10, 13, 26, 26, 909766, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
