# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-10 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysadmin', '0003_auto_20161010_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('1', 'warning'), ('2', 'info')], max_length=2)),
                ('message', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
