# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-10 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysadmin', '0004_systemupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemupdate',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
