# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-10 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysadmin', '0005_systemupdate_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemupdate',
            name='message_type',
            field=models.CharField(choices=[('1', 'warning'), ('2', 'info'), ('3', 'danger')], max_length=2),
        ),
    ]
