# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-18 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysadmin', '0007_emailupdate_from_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemupdate',
            name='visible_in_user_timeline',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='systemupdate',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
