# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-23 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysadmin', '0008_auto_20161018_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailupdate',
            name='sent',
        ),
        migrations.AddField(
            model_name='emailupdate',
            name='send_email',
            field=models.BooleanField(default=False),
        ),
    ]
