# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-23 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysadmin', '0009_auto_20161023_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailupdate',
            name='send_email',
        ),
        migrations.AddField(
            model_name='emailupdate',
            name='sent',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
