# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-24 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sysadmin', '0013_auto_20161024_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailupdate',
            name='sent',
        ),
    ]
