# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-28 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sysadmin', '0014_remove_emailupdate_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailIds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('email_id', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='emailgroup',
            name='users',
        ),
        migrations.AddField(
            model_name='emailids',
            name='emailgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emailids', to='sysadmin.EmailGroup'),
        ),
    ]
