# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-28 21:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sysadmin', '0015_auto_20161028_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailgroup',
            name='to_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
