# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-28 21:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysadmin', '0016_emailgroup_to_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailIds',
            new_name='EmailId',
        ),
        migrations.AlterField(
            model_name='emailgroup',
            name='to_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Site user'),
        ),
    ]
