# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-28 21:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sysadmin', '0017_auto_20161028_2143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailid',
            options={'verbose_name': 'Other email'},
        ),
    ]
