# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-28 21:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysadmin', '0019_auto_20161028_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailgroup',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to='csvs'),
        ),
        migrations.AlterField(
            model_name='emailgroup',
            name='to_users',
            field=models.ManyToManyField(blank=True, help_text="Site user's email id will be extracted by system automatically", null=True, to=settings.AUTH_USER_MODEL, verbose_name='Site user'),
        ),
    ]
