# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-28 22:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sysadmin', '0022_auto_20161028_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailgroup',
            old_name='to_users',
            new_name='users',
        ),
    ]
