# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-29 22:20
from __future__ import unicode_literals

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sysadmin', '0024_auto_20161029_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailupdate',
            name='image',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name='Image'),
        ),
    ]
