# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-29 22:33
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sysadmin', '0025_emailupdate_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailupdate',
            name='image',
        ),
        migrations.AlterField(
            model_name='emailupdate',
            name='message',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
