# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-30 14:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysadmin', '0026_auto_20161029_2233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailid',
            options={},
        ),
        migrations.AlterField(
            model_name='emailgroup',
            name='users',
            field=models.ManyToManyField(blank=True, help_text="Site user's email id will be added to emailids by system automatically", to=settings.AUTH_USER_MODEL, verbose_name='Site user'),
        ),
    ]
