# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 20:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usertimeline', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertimeline',
            old_name='receiver',
            new_name='reciever',
        ),
        migrations.RenameField(
            model_name='usertimeline',
            old_name='receiver_id',
            new_name='reciever_id',
        ),
    ]
