# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertimeline', '0002_auto_20160723_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertimeline',
            name='instruction',
            field=models.CharField(default='', max_length=200),
        ),
    ]
