# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 20:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usertimeline', '0004_usertimeline_not_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled_filters', jsonfield.fields.JSONField(default={'enabled': ['transfer', 'request', 'release', 'verified', 'unverified']})),
                ('click_counts', jsonfield.fields.JSONField(default={'release': 0, 'request': 0, 'transfer': 0, 'unverified': 0, 'verified': 0})),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timelinesetting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
