# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 06:44
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('usertimeline', '0005_timelinesetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelinesetting',
            name='enabled_filters',
            field=jsonfield.fields.JSONField(default={'enabled': ['1', '2', '3', '4', '5']}),
        ),
    ]
