# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertimeline', '0006_auto_20160729_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertimeline',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usertimeline',
            name='conn_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='usertimeline',
            name='conn_main',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='usertimeline',
            name='conn_sub',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='usertimeline',
            name='timeline_type',
            field=models.IntegerField(choices=[(1, 'transfer'), (2, 'request'), (3, 'release'), (4, 'verified'), (5, 'unverified'), (6, 'connection')]),
        ),
    ]
