# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 19:09
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('usertimeline', '0007_auto_20160804_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelinesetting',
            name='click_counts',
            field=jsonfield.fields.JSONField(default={'connection': 0, 'release': 0, 'request': 0, 'transfer': 0, 'unverified': 0, 'verified': 0}),
        ),
        migrations.AlterField(
            model_name='timelinesetting',
            name='enabled_filters',
            field=jsonfield.fields.JSONField(default={'enabled': ['1', '2', '3', '4', '5', '6']}),
        ),
    ]
