# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-03 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertimeline', '0009_auto_20160903_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertimeline',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='usertimeline',
            name='group_name',
        ),
        migrations.AlterField(
            model_name='usertimeline',
            name='timeline_type',
            field=models.IntegerField(choices=[(1, 'transfer'), (2, 'request'), (3, 'release'), (4, 'verified'), (5, 'unverified'), (6, 'connection')]),
        ),
    ]
