# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-18 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertimeline', '0012_auto_20161018_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertimeline',
            name='sysupdate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usertimeline',
            name='timeline_type',
            field=models.IntegerField(choices=[(1, 'transfer'), (2, 'request'), (3, 'release'), (4, 'verified'), (5, 'unverified'), (6, 'connection')]),
        ),
    ]
