# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-26 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertimeline', '0013_auto_20161018_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertimeline',
            name='timeline_type',
            field=models.IntegerField(choices=[(1, 'transfer'), (2, 'request'), (3, 'release'), (4, 'verified'), (5, 'unverified'), (6, 'connection'), (7, 'gcdistribute')]),
        ),
    ]
