# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-27 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertimeline', '0015_auto_20170426_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertimeline',
            name='amount',
            field=models.CharField(default='', max_length=200),
        ),
    ]
