# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-27 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertimeline', '0016_auto_20170427_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertimeline',
            name='amount',
            field=models.FloatField(),
        ),
    ]
