# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-27 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertimeline', '0017_auto_20170427_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertimeline',
            name='amount',
            field=models.FloatField(null=True),
        ),
    ]
