# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-10 18:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlaggedAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_gc_signup', models.BooleanField(default=False)),
                ('has_address', models.BooleanField(default=False)),
                ('has_name_fields', models.BooleanField(default=False)),
                ('has_avatar', models.BooleanField(default=False)),
                ('has_socials', models.BooleanField(default=False)),
                ('has_connections', models.BooleanField(default=False)),
                ('has_posts', models.BooleanField(default=False)),
                ('has_messages', models.BooleanField(default=False)),
                ('first_notice_sent_on', models.DateTimeField(blank=True, editable=False, null=True)),
                ('second_notice_sent_on', models.DateTimeField(blank=True, editable=False, null=True)),
                ('third_notice_sent_on', models.DateTimeField(blank=True, editable=False, null=True)),
                ('user_inactive', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
