# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicusers', '0002_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='connection_type_main',
            field=models.CharField(max_length=100),
        ),
    ]
