# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-14 10:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_ogtags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OgTags',
            new_name='OgTag',
        ),
    ]
