# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-14 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_newsogtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsogtag',
            name='news',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='landing.News'),
        ),
    ]
