# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-14 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_auto_20161014_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraMetaTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_tag', models.CharField(help_text='enter full og meta name', max_length=30)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='ogtag',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='ogtag',
            name='page_type',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='ogtag',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='ogtag',
            name='page',
            field=models.CharField(blank=True, choices=[('index', 'index'), ('hashtag', 'hashtag'), ('news', 'news')], help_text='Choose one if you want to link to one of landing pages', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ogtag',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='extrametatag',
            name='ogtag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.OgTag'),
        ),
    ]
