# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-14 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_auto_20161014_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogtag',
            name='app_id',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
