# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-15 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_ogtag_app_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalOgTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('title', models.CharField(default='', max_length=100)),
                ('page_type', models.CharField(default='', max_length=40)),
                ('description', models.CharField(default='', max_length=255)),
                ('app_id', models.CharField(blank=True, default='', max_length=40)),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='OgTagLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('index', 'index'), ('hashtag', 'hashtag'), ('news', 'news')], max_length=10)),
                ('globalogtag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.GlobalOgTag')),
            ],
        ),
        migrations.RemoveField(
            model_name='newsogtag',
            name='news',
        ),
        migrations.AlterField(
            model_name='extrametatag',
            name='ogtag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.GlobalOgTag'),
        ),
        migrations.DeleteModel(
            name='NewsOgTag',
        ),
        migrations.DeleteModel(
            name='OgTag',
        ),
        migrations.AddField(
            model_name='news',
            name='ogtag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='landing.GlobalOgTag'),
        ),
    ]
