# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-04 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0012_auto_20161031_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='draft',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
