# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-13 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0015_auto_20170313_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ogtaglink',
            name='globalogtag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='landing.GlobalOgTag'),
        ),
    ]
