# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-21 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0016_auto_20170313_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalogtag',
            name='keywords',
            field=models.CharField(blank=True, default='', help_text='Enter keywords separated by a ","', max_length=200),
        ),
    ]
