# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='instruction',
            field=models.CharField(default='', max_length=200),
        ),
    ]
