# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0002_transaction_instruction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='units',
            field=models.CharField(max_length=5),
        ),
    ]
