# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0006_auto_20160715_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='instruction',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='units',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
