# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0008_auto_20160715_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='units',
            field=models.IntegerField(),
        ),
    ]
