# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0009_auto_20160715_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='next_release',
            field=models.DateTimeField(),
        ),
    ]
