# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0011_auto_20160716_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='next_release',
            field=models.DateTimeField(),
        ),
    ]
