# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0013_requestunits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomerelease',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='requestunits',
            name='units',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='units',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='balance',
            field=models.PositiveIntegerField(default=1200),
        ),
    ]
