# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0014_auto_20160725_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='balance',
            field=models.PositiveIntegerField(default=1024),
        ),
    ]
