# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-12 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0015_auto_20160818_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='next_release',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='wallet_accont_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
