# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-20 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0016_auto_20170412_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='from_user',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='to_user',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
