# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-21 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0019_admindistribution_userdistribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='NextRelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
            ],
            options={
                'get_latest_by': 'id',
            },
        ),
    ]
