# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-26 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0023_distributionphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='admindistribution',
            name='log_file_path',
            field=models.CharField(default='', max_length=500),
        ),
    ]
