# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-05 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autosignup', '0034_auto_20170426_1008'),
        ('useraccount', '0024_admindistribution_log_file_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedDistributionBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('batch_number', models.IntegerField(null=True)),
                ('signups', models.ManyToManyField(to='autosignup.CommunitySignup')),
            ],
        ),
    ]
