# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-11 09:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('emailaddress', models.EmailField(max_length=254, null=True)),
                ('verified', models.BooleanField(default=False, editable=False)),
                ('verified_times', models.IntegerField(default=0, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='CarrierCSV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('csv', models.FileField(upload_to='carriercsvs')),
            ],
        ),
        migrations.CreateModel(
            name='Verifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailtosms.Carrier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carriers_verified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
