# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-05-02 10:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import emailtosms.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('emailaddress', models.EmailField(max_length=254, null=True)),
                ('tested', models.BooleanField(default=False, editable=False)),
                ('verified', models.BooleanField(default=False, editable=False)),
                ('verified_times', models.IntegerField(default=0, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='CarrierCSV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('csv', models.FileField(upload_to='carriercsvs')),
            ],
        ),
        migrations.CreateModel(
            name='UserCarrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('emailaddress', models.EmailField(blank=True, max_length=254, null=True)),
                ('added_to_carrier', models.BooleanField(default=False, editable=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_carrier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User requested carrier',
            },
        ),
        migrations.CreateModel(
            name='Verifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=emailtosms.models.random_string, max_length=10)),
                ('failed', models.BooleanField(default=True, editable=False)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailtosms.Carrier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carriers_verified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
