# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-12 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailtosms', '0002_verifier_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCarrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('emailaddress', models.EmailField(blank=True, max_length=254, null=True)),
                ('added_to_carrier', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'verbose_name': 'User requested carrier',
            },
        ),
    ]
