# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-15 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailtosms', '0003_usercarrier'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifier',
            name='failed',
            field=models.BooleanField(default=True),
        ),
    ]
