# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-15 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailtosms', '0004_verifier_failed'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='tested',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
