# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-15 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailtosms', '0005_carrier_tested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifier',
            name='failed',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
