# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-14 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrowdFund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('raised', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('ongoing', models.BooleanField(default=False)),
            ],
        ),
    ]
