# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-15 15:46
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0002_auto_20170215_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowdfund',
            name='goal',
            field=models.DecimalField(decimal_places=2, max_digits=30, validators=[django.core.validators.MinValueValidator(1.0)]),
        ),
    ]
