# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-15 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0003_auto_20170215_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowdfund',
            name='raised',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True),
        ),
    ]
