# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-16 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0004_auto_20170215_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crowdfund',
            old_name='ongoing',
            new_name='active',
        ),
    ]
