# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-16 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0005_auto_20170216_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowdfund',
            name='goal',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crowdfund',
            name='raised',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
