# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-05 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0006_auto_20170216_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowdfund',
            name='default_note',
            field=models.CharField(blank=True, default='', help_text='set a default note for the payment form', max_length=200),
        ),
    ]
