# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-05 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0007_crowdfund_default_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredefinedAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('default', models.BooleanField(default=False)),
                ('crowdfund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowdfunding.CrowdFund')),
            ],
        ),
    ]
