# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-06 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0008_predefinedamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowdfund',
            name='thankyou_message',
            field=models.TextField(blank=True, default='Thank You', help_text='Customize the payment form thank you message'),
        ),
    ]
