# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-06 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0010_auto_20170306_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('fa_icon_name', models.CharField(blank=True, default='cog', help_text='Add font Awesome icon name here', max_length=40)),
                ('fa_icon_color', models.CharField(blank=True, default='#f9f9f9', max_length=7)),
                ('crowdfund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowdfunding.CrowdFund')),
            ],
        ),
    ]
