# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-07 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0011_productfeature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfeature',
            name='fa_icon_color',
            field=models.CharField(blank=True, default='#9F9F9F', max_length=7),
        ),
    ]
