# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-07 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0012_auto_20170307_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfeature',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
