# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-08 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0013_auto_20170307_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='crowdfund_header_videos')),
                ('crowdfund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowdfunding.CrowdFund')),
            ],
        ),
    ]
