# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-08 17:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0014_headervideo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='headervideo',
            options={'get_latest_by': 'id'},
        ),
    ]
