# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-11 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0015_auto_20170308_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowdfund',
            name='cards_html',
            field=models.TextField(blank=True, default=''),
        ),
    ]
