# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-13 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0017_crowdfund_admin_cards_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfeature',
            name='linked_card',
            field=models.CharField(default='', max_length=100),
        ),
    ]
