# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-16 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0018_productfeature_linked_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowdfund',
            name='header_html',
            field=models.TextField(blank=True, default=''),
        ),
    ]
