# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-17 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0019_crowdfund_header_html'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardsVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(upload_to='crowdfund_videos')),
                ('video', models.FileField(upload_to='crowdfund_videos')),
                ('crowdfund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowdfunding.CrowdFund')),
            ],
            options={
                'get_latest_by': 'id',
            },
        ),
        migrations.RemoveField(
            model_name='headervideo',
            name='crowdfund',
        ),
        migrations.DeleteModel(
            name='HeaderVideo',
        ),
    ]
