# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-06 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0021_auto_20170317_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='crowdfund_images')),
                ('crowdfund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowdfunding.CrowdFund')),
            ],
            options={
                'get_latest_by': 'id',
            },
        ),
    ]
