# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 13:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserNotificaion',
            new_name='UserNotification',
        ),
    ]
