# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-03 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20160808_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='group_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='notification_type',
            field=models.IntegerField(choices=[(1, 'transfer'), (2, 'request'), (3, 'release'), (4, 'verified'), (5, 'unverified'), (6, 'connectionreq'), (7, 'connectioncancel'), (8, 'connectionaccept'), (9, 'connectionreject'), (10, 'disconnect'), (11, 'groupinvite')]),
        ),
    ]
