# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-08 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_auto_20161002_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='timeline_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
