# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-26 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0008_auto_20161018_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='notification_type',
            field=models.IntegerField(choices=[(1, 'transfer'), (2, 'request'), (3, 'release'), (4, 'verified'), (5, 'unverified'), (6, 'connectionreq'), (7, 'connectioncancel'), (8, 'connectionaccept'), (9, 'connectionreject'), (10, 'disconnect'), (11, 'groupinvite'), (12, 'groupjoinrequest'), (13, 'systemupdate'), (14, 'gcdistribute')]),
        ),
    ]
