# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-27 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0009_auto_20170426_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='amount',
            field=models.FloatField(null=True),
        ),
    ]
