# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilesystem', '0002_auto_20160720_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.IntegerField(blank=True, choices=[('1', 'Male'), ('2', 'Female')], null=True),
        ),
    ]
