# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilesystem', '0004_auto_20160725_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female')], default='', max_length=1),
        ),
    ]
