# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilesystem', '0012_auto_20160729_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='completion_public',
            field=models.BooleanField(default=True),
        ),
    ]
