# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilesystem', '0013_userprofile_completion_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Agender'), ('4', 'Androgyne'), ('5', 'Androgynous'), ('6', 'Bigender'), ('7', 'Cis'), ('8', 'Cisgender'), ('9', 'Cis Female'), ('10', 'Cis Male'), ('11', 'Cis Man'), ('12', 'Cis Woman'), ('13', 'Cisgender Female'), ('14', 'Cisgender Male'), ('15', 'Cisgender Man'), ('16', 'Cisgender Woman'), ('17', 'Female to Male'), ('18', 'FTM'), ('19', 'Gender Fluid'), ('20', 'Gender Nonconforming'), ('21', 'Gender Questioning'), ('22', 'Gender Variant'), ('23', 'Genderqueer'), ('24', 'Intersex'), ('25', 'Male to Female'), ('26', 'MTF'), ('27', 'Neither'), ('28', 'Neutrois'), ('29', 'Non-binary'), ('30', 'Other'), ('31', 'Pangender'), ('32', 'Trans'), ('33', 'Trans*'), ('34', 'Trans Female'), ('35', 'Trans* Female'), ('36', 'Trans Male'), ('37', 'Trans* Male'), ('38', 'Trans Man'), ('39', 'Trans* Man'), ('40', 'Trans Person'), ('41', 'Trans* Person'), ('42', 'Trans Woman'), ('43', 'Trans* Woman'), ('44', 'Transfeminine'), ('45', 'Transfeminine'), ('46', 'Transgender'), ('47', 'Transgender Female'), ('48', 'Transgender Male'), ('49', 'Transgender Man'), ('50', 'Transgender Person'), ('51', 'Transgender Woman'), ('52', 'Transmasculine'), ('53', 'Transsexual'), ('54', 'Transsexual Female'), ('55', 'Transsexual Male'), ('56', 'Transsexual Man'), ('57', 'Transsexual Person'), ('58', 'Transsexual Woman'), ('59', 'Two-Spirit')], default='', max_length=3),
        ),
    ]
