# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-27 07:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profilesystem', '0015_useruistate'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOneSignal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onesignalid', models.CharField(max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onesignals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
