# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-29 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilesystem', '0016_useronesignal'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='about_me',
            field=models.CharField(default='', max_length=300),
        ),
    ]
