# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-29 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilesystem', '0018_auto_20160929_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='invitation_verified',
            field=models.BooleanField(default=True),
        ),
    ]
