# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-29 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilesystem', '0019_userprofile_invitation_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='invitation_verified',
            field=models.BooleanField(default=False),
        ),
    ]
