# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-01 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profilesystem', '0020_auto_20160929_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='about_me',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='avatar', verbose_name='user avatar'),
        ),
    ]
