# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-02 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilesystem', '0021_auto_20161001_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='groups_link_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hashtagcampaign_link_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='information_link_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='messaging_link_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='timeline_link_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='users_link_visible',
            field=models.BooleanField(default=False),
        ),
    ]
