# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-09 18:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profilesystem', '0028_userprofile_referred_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
