# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-24 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilesystem', '0029_auto_20161209_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ekata_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
