# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-17 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilesystem', '0031_auto_20170219_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_avatar_color',
            field=models.CharField(blank=True, default='#7b1fa2', max_length=8),
        ),
    ]
