# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-05 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_versioninfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versioninfo',
            name='color',
            field=models.CharField(help_text='bg-colorname', max_length=20),
        ),
    ]
