# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-10 15:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0005_activemembercount_newmembercount_totalmembercount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activemembercount',
            name='count',
        ),
        migrations.AddField(
            model_name='activemembercount',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
