# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-10 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20170110_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activemembercount',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='newmembercount',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='totalmembercount',
            name='date',
            field=models.DateField(),
        ),
    ]
