# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-04 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20170110_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalMessageCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('date', models.DateField()),
            ],
        ),
    ]
