# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-05 18:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunitySignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community', models.CharField(choices=[('grantcoin', 'grantcoin')], max_length=100)),
                ('step_1_done', models.BooleanField(default=False)),
                ('step_2_done', models.BooleanField(default=False)),
                ('step_3_done', models.BooleanField(default=False)),
                ('additional_step_done', models.BooleanField(default=False)),
                ('signedup', models.BooleanField(default=False)),
                ('failed_auto_signup', models.BooleanField(default=False)),
                ('sent_to_community_staff', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='communitysignups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
