# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-05 19:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autosignup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitysignup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communitysignups', to=settings.AUTH_USER_MODEL),
        ),
    ]
