# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-05 22:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autosignup', '0002_auto_20161105_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerfication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='communitysignup',
            name='useremail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='emailverfication',
            name='community_signup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autosignup.CommunitySignup'),
        ),
        migrations.AddField(
            model_name='emailverfication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
