# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-08 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autosignup', '0004_auto_20161106_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communitysignup',
            old_name='signedup',
            new_name='verified',
        ),
        migrations.AddField(
            model_name='communitysignup',
            name='useraddress_from_twilio',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='communitysignup',
            name='useraddress_in_db',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='communitysignup',
            name='userimage',
            field=models.ImageField(null=True, upload_to='community_signup_user_images'),
        ),
    ]
