# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-14 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autosignup', '0005_auto_20161108_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('signup_is_open', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='communitysignup',
            name='additional_step_done',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='communitysignup',
            name='community',
            field=models.CharField(choices=[('grantcoin', 'grantcoin')], editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='communitysignup',
            name='failed_auto_signup',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='communitysignup',
            name='sent_to_community_staff',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='communitysignup',
            name='step_1_done',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='communitysignup',
            name='step_2_done',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='communitysignup',
            name='step_3_done',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='communitysignup',
            name='useraddress_from_twilio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='communitysignup',
            name='useraddress_in_db',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='communitysignup',
            name='useremail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='communitysignup',
            name='userimage',
            field=models.ImageField(blank=True, null=True, upload_to='community_signup_user_images'),
        ),
        migrations.AlterField(
            model_name='communitysignup',
            name='verified',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
