# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-18 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autosignup', '0007_communitysignup_useraddress_from_geoip'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='communitysignup',
            name='auto_signup_fail_reason',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='communitysignup',
            name='email_in_globaldb',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='communitysignup',
            name='phone_in_globaldb',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
