# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-19 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autosignup', '0008_auto_20161118_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communitysignup',
            old_name='verified',
            new_name='approved',
        ),
    ]
