# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-19 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autosignup', '0010_communitysignup_data_collect_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountAddContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=100, verbose_name='Name of organization')),
                ('proposal', models.TextField()),
            ],
            options={
                'verbose_name': 'Account proposal',
            },
        ),
    ]
