# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-19 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autosignup', '0011_accountaddcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountaddcontact',
            name='emailaddress',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
