# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-20 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autosignup', '0012_accountaddcontact_emailaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitysignup',
            name='approved',
        ),
        migrations.AddField(
            model_name='communitysignup',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=100),
        ),
    ]
