# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-20 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autosignup', '0013_auto_20161120_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitysignup',
            name='useraddress_in_db',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='communitysignup',
            name='useremail',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='communitysignup',
            name='userphone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Phone'),
        ),
    ]
