# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-28 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autosignup', '0018_auto_20161128_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedMailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.FileField(upload_to='mailtemplate')),
                ('selected', models.BooleanField(default=False)),
                ('accountprovider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailtemplate', to='autosignup.AccountProvider')),
            ],
        ),
    ]
