# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-01 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autosignup', '0020_auto_20161130_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitysignup',
            name='email_in_globaldb',
        ),
        migrations.RemoveField(
            model_name='communitysignup',
            name='phone_in_globaldb',
        ),
        migrations.RemoveField(
            model_name='historicalcommunitysignup',
            name='email_in_globaldb',
        ),
        migrations.RemoveField(
            model_name='historicalcommunitysignup',
            name='phone_in_globaldb',
        ),
        migrations.AddField(
            model_name='globalemail',
            name='signup',
            field=models.ManyToManyField(related_name='globalemail', to='autosignup.CommunitySignup'),
        ),
        migrations.AddField(
            model_name='globalphone',
            name='signup',
            field=models.ManyToManyField(related_name='globalphone', to='autosignup.CommunitySignup'),
        ),
    ]
