# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-02 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autosignup', '0022_auto_20161201_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountProviderCSV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv', models.FileField(null=True, upload_to='membercsv')),
                ('processed', models.BooleanField(default=False)),
                ('accountprovider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autosignup.AccountProvider')),
            ],
        ),
        migrations.AddField(
            model_name='communitysignup',
            name='is_on_distribution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='communitysignup',
            name='referral_code',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='communitysignup',
            name='signup_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='communitysignup',
            name='verified_date',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='communitysignup',
            name='wallet_address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='historicalcommunitysignup',
            name='is_on_distribution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcommunitysignup',
            name='referral_code',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='historicalcommunitysignup',
            name='signup_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalcommunitysignup',
            name='verified_date',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalcommunitysignup',
            name='wallet_address',
            field=models.CharField(default='', max_length=100),
        ),
    ]
