# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-03 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autosignup', '0024_auto_20161202_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountprovider',
            name='basicgroup',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_signups', to='groupsystem.BasicGroup'),
        ),
    ]
