# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-03 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autosignup', '0025_auto_20161203_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountprovider',
            name='allowed_distance',
            field=models.IntegerField(blank=True, default=20, editable=False),
        ),
        migrations.AlterField(
            model_name='accountprovider',
            name='signup_is_open',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
