# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-04 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autosignup', '0026_auto_20161203_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitysignup',
            name='image_gps_metadata',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcommunitysignup',
            name='image_gps_metadata',
            field=models.TextField(blank=True, null=True),
        ),
    ]
