# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-04 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autosignup', '0027_auto_20161204_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitysignup',
            name='referral_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='communitysignup',
            name='referred_by',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='communitysignup',
            name='wallet_address',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcommunitysignup',
            name='referral_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcommunitysignup',
            name='referred_by',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcommunitysignup',
            name='wallet_address',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
