# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-04 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autosignup', '0028_auto_20161204_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprovidercsv',
            name='failed_csv',
            field=models.FileField(null=True, upload_to='membercsv'),
        ),
    ]
