# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-08 07:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autosignup', '0029_accountprovidercsv_failed_csv'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_code', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='communitysignup',
            name='referral_code',
        ),
        migrations.RemoveField(
            model_name='communitysignup',
            name='referred_by',
        ),
        migrations.RemoveField(
            model_name='historicalcommunitysignup',
            name='referral_code',
        ),
        migrations.RemoveField(
            model_name='historicalcommunitysignup',
            name='referred_by',
        ),
        migrations.AlterField(
            model_name='communitysignup',
            name='useraddress_in_db',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcommunitysignup',
            name='useraddress_in_db',
            field=models.TextField(blank=True, null=True),
        ),
    ]
