# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-08 11:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autosignup', '0030_auto_20161208_0747'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoSignupAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('db', 'db'), ('twilio', 'twilio'), ('geoip', 'geoip')], max_length=20)),
                ('house_number', models.CharField(blank=True, default='', max_length=10)),
                ('street', models.CharField(blank=True, default='', max_length=200)),
                ('zip_code', models.CharField(blank=True, default='', max_length=10)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('latitude', models.CharField(blank=True, default='', max_length=100)),
                ('longitude', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='communitysignup',
            name='useraddress_from_geoip',
        ),
        migrations.RemoveField(
            model_name='communitysignup',
            name='useraddress_from_twilio',
        ),
        migrations.RemoveField(
            model_name='communitysignup',
            name='useraddress_in_db',
        ),
        migrations.RemoveField(
            model_name='historicalcommunitysignup',
            name='useraddress_from_geoip',
        ),
        migrations.RemoveField(
            model_name='historicalcommunitysignup',
            name='useraddress_from_twilio',
        ),
        migrations.RemoveField(
            model_name='historicalcommunitysignup',
            name='useraddress_in_db',
        ),
        migrations.AddField(
            model_name='autosignupaddress',
            name='signup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='useraddresses', to='autosignup.CommunitySignup'),
        ),
        migrations.AddField(
            model_name='autosignupaddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
