# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-24 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autosignup', '0032_auto_20161210_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitysignup',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('incomplete', 'Incomplete')], default='incomplete', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcommunitysignup',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('incomplete', 'Incomplete')], default='incomplete', max_length=100),
        ),
    ]
