# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-26 10:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('autosignup', '0033_auto_20170124_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralcode',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 4, 26, 10, 8, 45, 186250, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referralcode',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
