# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-16 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=300)),
                ('b_type', models.CharField(blank=True, default='', max_length=300)),
                ('path', models.CharField(blank=True, default='', max_length=300)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NextBackup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_on', models.DateTimeField()),
            ],
            options={
                'get_latest_by': 'id',
            },
        ),
    ]
