# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-01 19:24
from __future__ import unicode_literals

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('groupsystem', '0002_auto_20160901_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicgroup',
            name='header_image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='group_headers'),
        ),
        migrations.AlterField(
            model_name='basicgroup',
            name='logo',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='group_logos'),
        ),
    ]
