# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-03 07:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupsystem', '0005_auto_20160902_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppost',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
