# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-03 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupsystem', '0006_auto_20160903_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupnews',
            name='news',
            field=models.TextField(verbose_name='Content'),
        ),
    ]
