# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-05 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupsystem', '0010_auto_20160905_0845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basicgroup',
            options={'permissions': (('can_access_admin', 'Can access admin'), ('can_read_news', 'Can read news'), ('can_create_news', 'Can create news'), ('can_read_post', 'Can read post'), ('can_create_post', 'Can create post'))},
        ),
    ]
