# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-05 21:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupsystem', '0011_auto_20160905_2053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basicgroup',
            options={'permissions': (('can_access_admin', 'Can access admin'), ('can_read_news', 'Can read news'), ('can_create_news', 'Can create news'), ('can_update_news', 'Can update news'), ('can_read_post', 'Can read post'), ('can_create_post', 'Can create post'), ('can_update_post', 'Can update post'), ('can_approve_post', 'Can approve post'), ('can_read_comment', 'Can read comment'), ('can_create_comment', 'Can create comment'), ('can_update_comment', 'Can update comment'), ('can_approve_comment', 'Can approve comment'), ('can_like_post', 'Can like post'), ('can_create_notification', 'Can create notification'), ('can_create_invite', 'Can create invite'), ('can_add_member', 'Can add member'), ('can_read_events', 'Can read events'), ('can_create_events', 'Can create events'), ('can_update_events', 'Can update events'), ('can_read_joinrequest', 'Can read join requests'), ('can_approve_joinrequest', 'Can approve join requests'))},
        ),
    ]
