# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-06 08:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groupsystem', '0012_auto_20160905_2130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basicgroup',
            options={'permissions': (('can_access_admin', 'Can access admin'), ('can_read_news', 'Can read news'), ('can_create_news', 'Can create news'), ('can_update_news', 'Can update news'), ('can_delete_news', 'Can delete news'), ('can_read_post', 'Can read post'), ('can_create_post', 'Can create post'), ('can_update_post', 'Can update post'), ('can_approve_post', 'Can approve post'), ('can_delete_post', 'Can delete post'), ('can_read_comment', 'Can read comment'), ('can_create_comment', 'Can create comment'), ('can_update_comment', 'Can update comment'), ('can_approve_comment', 'Can approve comment'), ('can_delete_comment', 'Can delete comment'), ('can_like_post', 'Can like post'), ('can_create_notification', 'Can create notification'), ('can_create_invite', 'Can create invite'), ('can_add_member', 'Can add member'), ('can_remove_member', 'Can remove member'), ('can_read_events', 'Can read events'), ('can_create_events', 'Can create events'), ('can_update_events', 'Can update events'), ('can_delete_events', 'Can delete events'), ('can_read_joinrequest', 'Can read join requests'), ('can_approve_joinrequest', 'Can approve join requests'), ('can_deny_joinrequest', 'Can deny joinrequest'))},
        ),
        migrations.AddField(
            model_name='basicgroup',
            name='banned_members',
            field=models.ManyToManyField(related_name='banned_group', to=settings.AUTH_USER_MODEL),
        ),
    ]
