# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-06 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupsystem', '0014_auto_20160906_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinrequest',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
