# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-06 15:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupsystem', '0015_joinrequest_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_role', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='basicgroup',
            name='default_roles',
            field=models.TextField(default='superadmin;admin;moderator;member;subscriber'),
        ),
        migrations.AlterField(
            model_name='basicgroup',
            name='banned_members',
            field=models.ManyToManyField(related_name='banned_group', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customrole',
            name='basic_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customrole', to='groupsystem.BasicGroup'),
        ),
    ]
