# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 22:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groupsystem', '0019_auto_20160907_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMemberExtraPerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_access_admin', models.BooleanField(default=False)),
                ('can_read_news', models.BooleanField(default=False)),
                ('can_create_news', models.BooleanField(default=False)),
                ('can_update_news', models.BooleanField(default=False)),
                ('can_delete_news', models.BooleanField(default=False)),
                ('can_read_post', models.BooleanField(default=False)),
                ('can_create_post', models.BooleanField(default=False)),
                ('can_update_post', models.BooleanField(default=False)),
                ('can_approve_post', models.BooleanField(default=False)),
                ('can_delete_post', models.BooleanField(default=False)),
                ('can_read_comment', models.BooleanField(default=False)),
                ('can_create_comment', models.BooleanField(default=False)),
                ('can_update_comment', models.BooleanField(default=False)),
                ('can_approve_comment', models.BooleanField(default=False)),
                ('can_delete_comment', models.BooleanField(default=False)),
                ('can_like_post', models.BooleanField(default=False)),
                ('can_create_notification', models.BooleanField(default=False)),
                ('can_create_invite', models.BooleanField(default=False)),
                ('can_add_member', models.BooleanField(default=False)),
                ('can_remove_member', models.BooleanField(default=False)),
                ('can_ban_member', models.BooleanField(default=False)),
                ('can_lift_member_ban', models.BooleanField(default=False)),
                ('can_read_events', models.BooleanField(default=False)),
                ('can_create_events', models.BooleanField(default=False)),
                ('can_update_events', models.BooleanField(default=False)),
                ('can_delete_events', models.BooleanField(default=False)),
                ('can_read_joinrequest', models.BooleanField(default=False)),
                ('can_approve_joinrequest', models.BooleanField(default=False)),
                ('can_deny_joinrequest', models.BooleanField(default=False)),
                ('can_edit_group_profile', models.BooleanField(default=False)),
                ('can_read_role', models.BooleanField(default=False)),
                ('can_read_custom_role', models.BooleanField(default=False)),
                ('can_update_custom_role', models.BooleanField(default=False)),
                ('can_create_custom_role', models.BooleanField(default=False)),
                ('basic_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberextraperm', to='groupsystem.BasicGroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
