# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-01 19:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groupsystem', '0023_auto_20160909_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicgroup',
            name='super_admin',
        ),
        migrations.AddField(
            model_name='basicgroup',
            name='super_admins',
            field=models.ManyToManyField(related_name='basicgroups', to=settings.AUTH_USER_MODEL),
        ),
    ]
