# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-01 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupsystem', '0024_auto_20161001_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicgroup',
            name='default_roles',
            field=models.TextField(default='superadmin;admin;moderator;member;subscriber', editable=False),
        ),
    ]
