# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-02 07:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groupsystem', '0025_auto_20161001_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicgroup',
            name='admins',
            field=models.ManyToManyField(related_name='administerd_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='basicgroup',
            name='moderators',
            field=models.ManyToManyField(related_name='moderating_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
