# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-18 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupsystem', '0027_auto_20161016_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicgroup',
            name='auto_approve_comment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='basicgroup',
            name='auto_approve_post',
            field=models.BooleanField(default=True),
        ),
    ]
