# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-01 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupsystem', '0028_auto_20161218_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicgroup',
            name='is_beta_test_group',
            field=models.BooleanField(default=False),
        ),
    ]
