# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-20 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupsystem', '0029_basicgroup_is_beta_test_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicgroup',
            name='group_type',
            field=models.CharField(choices=[('1', 'Art'), ('2', 'Activist'), ('3', 'Political'), ('4', 'News'), ('5', 'Business'), ('6', 'Government'), ('7', 'Blog'), ('8', 'Nonprofit Organization'), ('9', 'Other')], max_length=30, verbose_name='Group Type'),
        ),
        migrations.AlterField(
            model_name='basicgroup',
            name='long_about',
            field=models.TextField(blank=True, null=True, verbose_name='Long About'),
        ),
        migrations.AlterField(
            model_name='basicgroup',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='basicgroup',
            name='short_about',
            field=models.CharField(max_length=300, verbose_name='Short About'),
        ),
    ]
