# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-02-09 17:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groupsystem', '0030_auto_20170220_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicgroup',
            name='blocked_members',
            field=models.ManyToManyField(related_name='blocked_group', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='basicgroup',
            name='staff',
            field=models.ManyToManyField(related_name='staff_in_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
