# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-02-14 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupsystem', '0032_auto_20180209_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicgroup',
            name='join_status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('request', 'Request'), ('invite', 'Invite')], default='request', max_length=30),
        ),
    ]
