# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-02-16 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupsystem', '0033_basicgroup_join_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupnotification',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
    ]
