# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-02-24 15:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groupsystem', '0035_auto_20180217_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMemberNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=True)),
                ('object_id', models.PositiveIntegerField()),
                ('basic_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupsystem.BasicGroup')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_member_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
