# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-02-24 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupsystem', '0036_groupmembernotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmembernotification',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
