# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-02-26 20:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groupsystem', '0037_auto_20180224_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteAccept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_invite', to='groupsystem.BasicGroup')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_accept', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
