# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-02-27 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupsystem', '0038_inviteaccept'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicgroup',
            name='flagged_for_deletion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basicgroup',
            name='flagged_for_deletion_on',
            field=models.DateTimeField(null=True),
        ),
    ]
