# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-03-07 20:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupsystem', '0039_auto_20180227_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouppost',
            name='admin_created',
        ),
        migrations.RemoveField(
            model_name='grouppost',
            name='title',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='basic_group',
        ),
        migrations.AlterField(
            model_name='grouppost',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts_approved', to=settings.AUTH_USER_MODEL),
        ),
    ]
