# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-29 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('invitation_id', models.CharField(max_length=300)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
