# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-29 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitationsystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
