# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-29 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitationsystem', '0002_auto_20160929_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='sent',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='invitation_id',
            field=models.CharField(editable=False, max_length=300),
        ),
    ]
