# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-06 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitationsystem', '0003_auto_20160929_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
