# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-06 23:20
from __future__ import unicode_literals

from django.db import migrations, models
import invitationsystem.models


class Migration(migrations.Migration):

    dependencies = [
        ('invitationsystem', '0005_auto_20161006_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='invitation_id',
            field=models.CharField(default=invitationsystem.models.random_string, editable=False, max_length=300),
        ),
    ]
