# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-03 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitationsystem', '0006_auto_20161006_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='invitation_type',
            field=models.CharField(choices=[('default', 'default'), ('grantcoin', 'grantcoin')], default='default', max_length=40),
        ),
        migrations.AddField(
            model_name='invitation',
            name='password',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='invitation',
            name='username',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
    ]
