# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-13 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitationsystem', '0008_auto_20161210_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='production_created',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
