# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-14 17:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('is_success', models.BooleanField(default=False)),
                ('message', models.CharField(default='', max_length=250)),
                ('payment_type', models.CharField(default='', max_length=100)),
                ('fail_reason', models.CharField(default='', max_length=300)),
                ('charge_id', models.CharField(default='', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
