# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-15 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripepayment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
