# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-22 21:12
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=300)),
                ('subject', models.CharField(max_length=100)),
                ('message', ckeditor_uploader.fields.RichTextUploadingField()),
                ('from_email', models.EmailField(choices=[('support@ekata.social', 'support@ekata.social'), ('news@ekata.social', 'news@ekata.social'), ('newsletter@ekata.social', 'newsletter@ekata.social')], default='support@ekata.social', max_length=254)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('csv_file', models.FileField(blank=True, null=True, upload_to='csvs')),
                ('users', models.ManyToManyField(blank=True, help_text="Site user's email id will be added to emailids by system automatically", related_name='emailgroups', to=settings.AUTH_USER_MODEL, verbose_name='Site user')),
            ],
        ),
        migrations.CreateModel(
            name='EmailId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('email_id', models.EmailField(max_length=254, null=True)),
                ('send_email_from_group', models.BooleanField(default=True)),
                ('send_email_from_ekata', models.BooleanField(default=True)),
                ('emailgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emailids', to='eblast.EmailGroup')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('template', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='template',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='eblast.EmailTemplate'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='to_groups',
            field=models.ManyToManyField(to='eblast.EmailGroup'),
        ),
    ]
