# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-29 22:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eblast', '0002_auto_20161228_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailgroup',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to='csvs', verbose_name='CSV Upload List'),
        ),
        migrations.AlterField(
            model_name='emailgroup',
            name='name',
            field=models.CharField(max_length=200, verbose_name='List Name'),
        ),
        migrations.AlterField(
            model_name='emailgroup',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='emailgroups', to=settings.AUTH_USER_MODEL, verbose_name='Select from List'),
        ),
    ]
