# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-31 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eblast', '0003_auto_20161229_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='html_file',
            field=models.FileField(blank=True, null=True, upload_to='emailtemplates'),
        ),
    ]
