# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-31 05:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eblast', '0004_emailtemplate_html_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='template',
        ),
    ]
