# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-31 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eblast', '0005_remove_emailtemplate_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='html_file',
            field=models.FileField(null=True, upload_to='emailtemplates'),
        ),
    ]
