# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-31 05:38
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eblast', '0006_auto_20161231_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='template',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='txet'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='html_file',
            field=models.FileField(blank=True, null=True, upload_to='emailtemplates'),
        ),
    ]
