# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-31 06:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eblast', '0008_auto_20161231_0620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='template',
        ),
    ]
