# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-31 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupsystem', '0028_auto_20161218_1641'),
        ('eblast', '0009_remove_emailtemplate_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailgroup',
            name='basic_group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groupsystem.BasicGroup', verbose_name='Link to Group'),
        ),
    ]
