# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-31 18:20
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eblast', '0010_emailgroup_basic_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='template',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
