# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-01 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eblast', '0013_auto_20170101_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='draft',
            field=models.BooleanField(default=True),
        ),
    ]
