# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-02 08:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eblast', '0014_emailcampaign_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailcampaign',
            name='from_email',
        ),
        migrations.RemoveField(
            model_name='emailcampaign',
            name='to_groups',
        ),
    ]
