# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-02 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eblast', '0015_auto_20170102_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcampaign',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eblast.EmailTemplate'),
        ),
    ]
