# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-02 16:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import eblast.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eblast', '0016_auto_20170102_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent', models.BooleanField(default=False)),
                ('opened', models.BooleanField(default=False)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('tracking_id', models.CharField(default=eblast.models.random_string, editable=False, max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='total_opened',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='total_sent',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='tracking_id',
            field=models.CharField(default=eblast.models.random_string, editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='campaigntracking',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eblast.EmailCampaign'),
        ),
        migrations.AddField(
            model_name='campaigntracking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
