# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-02 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eblast', '0017_auto_20170102_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigntracking',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackings', to='eblast.EmailCampaign'),
        ),
    ]
