# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-02 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eblast', '0018_auto_20170102_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailcampaign',
            name='total_opened',
        ),
        migrations.RemoveField(
            model_name='emailcampaign',
            name='total_sent',
        ),
    ]
