# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-02 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eblast', '0019_auto_20170102_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaigntracking',
            name='user',
        ),
        migrations.AddField(
            model_name='campaigntracking',
            name='emailid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eblast.EmailId'),
        ),
    ]
