# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-02 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eblast', '0020_auto_20170102_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigntracking',
            name='emailid',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
