# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-06 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eblast', '0022_auto_20170105_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='html_file',
            field=models.FileField(blank=True, null=True, upload_to='emailtemplates', verbose_name='HTML File'),
        ),
    ]
