# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-01 18:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messagingsystem', '0002_auto_20160817_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='unsubscribers',
            field=models.ManyToManyField(related_name='unsubscribed_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
