# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-12-27 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagingsystem', '0004_chatroom_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachment_path',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_type',
            field=models.CharField(default='', max_length=40),
        ),
    ]
